const languages = {
    pt: {
        myJourney: "Minha Jornada",
        technologies: "Tecnologias",
        findMe: "Onde me Encontrar",
		am: "Sou",
		developer: "desenvolvedor",
        aboutMe: "Sou desenvolvedor frontend em JavaScript formado em Ciência da Computação e estou sempre buscando novos desafios. Sou um entusiasta da tecnologia e sempre me atualizo com as novidades do mundo tecnológico.",
		myProjects: "Meus Projetos",
		myJourneyHow: "Minha Jornada como",
		resume: "Iniciei minha jornada profissional na vilaaps, onde tive meu primeiro contato com programação. Em seguida, fui contratado pela Recovery, onde programei um servidor de GTARP chamado Recovery City. Este servidor foi patrocinado pela John John para uma campanha publicitária chamada Drop Your Jeans. Posteriormente, ingressei na Multicast como back-end, onde participei do desenvolvimento de um totem de atendimento para a Unimed. Atualmente, sou desenvolvedor pleno na Growth Venture, onde implemento interfaces que são desenvolvidas pela equipe de design e realizo correções de bugs.",
		frontDeveloperMid: "Desenvolvedor Front-End - Pleno",
		firstWork: 'Em minha primeira experiência como desenvolvedor pleno, participei do lançamento de diversos projetos, contribuindo para o desenvolvimento do front-end e exercendo autonomia na escolha de algumas tecnologias. Além disso, realizei algumas correções e implementações no backend.',
		backendDeveloperJunior: "Desenvolvedor Back-End - Junior",
		secondWork: 'Contribuí no desenvolvimento de um totem de atendimento destinado à área da saúde. Na implementação da API, utilizei NodeJS, enquanto no front-end utilizei Vue.',
		frontDevelopJunior: 'Desenvolvedor Front-end - Junior',
		thirdWork: 'Desempenhei o papel de responsável pelo desenvolvimento completo do front-end de um servidor de GTA RP. Além disso, tive a oportunidade de participar de uma das maiores campanhas virtuais da John John, intitulada "Drop Your Jeans".',
		internshipDeveloper: 'Desenvolvedor Front-end - Estágio',
		fourthWork: 'Iniciei minha trajetória profissional como desenvolvedor, tendo minha primeira experiência prática com tecnologias como React, React Native, HTML, CSS e JavaScript',
		main: 'Principais',
		technologies: 'Tecnologias',
		tecnnologiesResume: ' Meu primeiro contato com uma linguagem de programação foi através do C durante a faculdade, e desde então, me apaixonei pela área. Ao longo do tempo, fui aprimorando meus conhecimentos e descobrindo novas tecnologias. Entre elas, destaco o JavaScript, que se tornou minha linguagem de programação principal.',
		creative: 'Creative',
		programming: 'Programação',
		digital: 'Digital',
		where: 'Onde me',
		find: 'Encontrar',
	},
	en: {
        myJourney: "My Journey",
        technologies: "Technologies",
        findMe: "Where to Find Me",
        am: "I am",
        developer: "a developer",
        aboutMe: "I am a frontend developer in JavaScript, graduated in Computer Science and always looking for new challenges. I am a technology enthusiast and always keep up with the news in the tech world.",
        myProjects: "My Projects",
        myJourneyHow: "My Journey as",
        resume: "I started my professional journey at VilaApps, where I had my first contact with programming. Then, I was hired by Recovery, where I programmed a GTARP server called Recovery City. This server was sponsored by John John for an advertising campaign called Drop Your Jeans. Later, I joined Multicast as a back-end, where I participated in the development of a service kiosk for Unimed. Currently, I am a full developer at Growth Venture, where I implement interfaces that are developed by the design team and carry out bug fixes.",
        frontDeveloperMid: "Front-End Developer - Mid",
        firstWork: "In my first experience as a mid-level developer, I participated in the launch of various projects, contributing to the development of the front-end and exercising autonomy in the choice of some technologies. Additionally, I made some corrections and implementations in the backend.",
        backendDeveloperJunior: "Back-End Developer - Junior",
        secondWork: "I contributed to the development of a service kiosk for the healthcare sector. In the API implementation, I used NodeJS, while in the front-end I used Vue.",
        frontDevelopJunior: "Front-end Developer - Junior",
        thirdWork: "I played the role of being responsible for the complete development of the front-end of a GTA RP server. In addition, I had the opportunity to participate in one of the largest virtual campaigns of John John, titled 'Drop Your Jeans'.",
        internshipDeveloper: "Front-end Developer - Intern",
        fourthWork: "I began my professional journey as a developer, having my first practical experience with technologies like React, React Native, HTML, CSS, and JavaScript",
        main: "Main",
        technologies: "Technologies",
        tecnnologiesResume: "My first contact with a programming language was through C during college, and since then, I have fallen in love with the field. Over time, I have been improving my skills and discovering new technologies. Among them, I highlight JavaScript, which has become my main programming language.",
        creative: "Creative",
        programming: "Programming",
        digital: "Digital",
        where: "Where to",
        find: "Find",
    }
};